### ISSUE TITLE
Runtime when manually changing name in character creator

### ISSUE THREAD

**Issue by triplezeta** [Haven-13/Haven-Urist#86] opened 2021-09-25 18:33 UTC
#### Description of issue

Attempting to change the name of your character as a machine (race) does nothing

#### Difference between expected and actual behavior

Name should have changed :(

#### Steps to reproduce 

change race to machine

attempt to change name

#### Specific information for locating

??

#### Length of time in which bug has been known to occur

happened during the playtest this morning/last night

#### Client version, Server revision & Game ID

514.1557 for client and server

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues) **i didnt check lol**

**Comment by martinlyra** [comment] 2021-09-25 18:53
![image](https://user-images.githubusercontent.com/13331724/134783097-5653ae16-d3d1-4980-bcd7-328004ac2cbf.png)

**Comment by martinlyra** [comment] 2021-09-25 18:58
This bug is caused by every race available in this codebase. So it is not unique to IPCs. But random names work, for some reason.

**Comment by martinlyra** [comment] 2021-09-25 22:16
Actually. Turns out the problem being applied to all species is because of me playing on the example map. The cultures are disabled when using it.

But on the main map, it is present because one cultural_info for the positronics/machine are missing.

**Comment by martinlyra** [comment] 2021-09-25 22:35
Closing this in relation to the #88 PR

**Closed by martinlyra** 2021-09-25 22:35 UTC
Labels: Bug, Runtime
